name: Pipeline

on: push

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: generate random string
        run: echo IMAGE_TAG=tag-$(date +%s) >> $GITHUB_ENV
        
      - name: print tag
        run: echo ${{ env.IMAGE_TAG }}

  test-var:
    needs: unit-tests
    runs-on: ubuntu-latest
    steps:
      - name: print tag
        run: echo ${{ env.IMAGE_TAG }}
